version: '2'

services:
  node:
    image: node:argon
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
